-- 6. Inserir exercícios para a categoria 'ponto-virgula-5' (Exercício 5)
INSERT INTO exercises (category_id, question, explanation, difficulty) VALUES
('ponto-virgula-5', 'Identifique a alternativa em que o ponto e vírgula está sendo usado corretamente em um caso especial:', 'O ponto e vírgula tem usos especiais em diferentes contextos, como em documentos oficiais, textos jurídicos e científicos.', 5),
('ponto-virgula-5', 'Em qual das opções o ponto e vírgula está sendo usado corretamente em um texto jurídico?', 'Em textos jurídicos, o ponto e vírgula é usado para separar considerandos ou itens em uma enumeração.', 5),
('ponto-virgula-5', 'Qual alternativa apresenta o uso correto do ponto e vírgula em um texto literário?', 'Em textos literários, o ponto e vírgula é usado para criar pausas mais longas que a vírgula, mas menos definitivas que o ponto.', 5),
('ponto-virgula-5', 'Identifique a frase em que o ponto e vírgula está sendo usado corretamente em um texto científico:', 'Em textos científicos, o ponto e vírgula é usado para separar diferentes aspectos de um mesmo tema.', 5),
('ponto-virgula-5', 'Em qual frase o ponto e vírgula está sendo usado corretamente em um documento oficial?', 'Em documentos oficiais, o ponto e vírgula é usado para separar considerandos ou justificativas.', 5),
('ponto-virgula-5', 'Qual alternativa apresenta o uso correto do ponto e vírgula em uma citação direta?', 'Em citações diretas, o ponto e vírgula é usado para separar diferentes partes da citação.', 5),
('ponto-virgula-5', 'Identifique a opção em que o ponto e vírgula está sendo usado corretamente em um texto filosófico:', 'Em textos filosóficos, o ponto e vírgula é usado para separar diferentes argumentos ou ideias.', 5),
('ponto-virgula-5', 'Em qual das opções o ponto e vírgula está sendo usado corretamente em um texto técnico?', 'Em textos técnicos, o ponto e vírgula é usado para separar diferentes especificações ou características.', 5),
('ponto-virgula-5', 'Qual alternativa apresenta o uso correto do ponto e vírgula em uma referência bibliográfica?', 'Em referências bibliográficas, o ponto e vírgula é usado para separar diferentes autores ou obras.', 5),
('ponto-virgula-5', 'Identifique a frase em que o ponto e vírgula está sendo usado corretamente em um texto acadêmico:', 'Em textos acadêmicos, o ponto e vírgula é usado para separar diferentes argumentos ou evidências.', 5);

-- 7. Inserir exercícios para a categoria 'prova-ponto-virgula' (Prova Final)
INSERT INTO exercises (category_id, question, explanation, difficulty) VALUES
('prova-ponto-virgula', 'Identifique a alternativa em que o ponto e vírgula está sendo usado corretamente:', 'O ponto e vírgula é usado para separar orações coordenadas não unidas por conjunção, especialmente quando são extensas.', 5),
('prova-ponto-virgula', 'Em qual das opções o ponto e vírgula está sendo usado corretamente antes de conjunções adversativas?', 'O ponto e vírgula é usado antes de conjunções adversativas como "mas", "porém", "contudo", "entretanto".', 5),
('prova-ponto-virgula', 'Qual alternativa apresenta o uso correto do ponto e vírgula em uma enumeração complexa?', 'O ponto e vírgula é usado para separar itens em uma enumeração quando os itens já contêm vírgulas.', 5),
('prova-ponto-virgula', 'Identifique a frase em que o ponto e vírgula está sendo usado corretamente antes de expressões explicativas:', 'O ponto e vírgula pode ser usado antes de expressões explicativas como "isto é", "ou seja", "a saber".', 5),
('prova-ponto-virgula', 'Em qual frase o ponto e vírgula está sendo usado corretamente para separar orações coordenadas extensas?', 'O ponto e vírgula é usado para separar orações coordenadas extensas, especialmente quando já contêm vírgulas.', 5),
('prova-ponto-virgula', 'Qual alternativa apresenta o uso correto do ponto e vírgula antes de conjunções conclusivas?', 'O ponto e vírgula é usado antes de conjunções conclusivas como "logo", "portanto", "por isso".', 5),
('prova-ponto-virgula', 'Identifique a opção em que o ponto e vírgula está sendo usado corretamente em um texto jurídico:', 'Em textos jurídicos, o ponto e vírgula é usado para separar itens em uma enumeração ou considerandos.', 5),
('prova-ponto-virgula', 'Em qual das opções o ponto e vírgula está sendo usado corretamente em uma lista bibliográfica?', 'Em listas bibliográficas, o ponto e vírgula é usado para separar diferentes referências.', 5),
('prova-ponto-virgula', 'Qual alternativa apresenta o uso correto do ponto e vírgula em um texto científico?', 'Em textos científicos, o ponto e vírgula é usado para separar diferentes aspectos de um mesmo tema.', 5),
('prova-ponto-virgula', 'Identifique a frase em que o ponto e vírgula está sendo usado corretamente em um documento oficial:', 'Em documentos oficiais, o ponto e vírgula é usado para separar considerandos ou justificativas.', 5);

-- 8. Inserir mais 20 exercícios para a categoria 'prova-ponto-virgula' (Prova Final) para completar os 30
INSERT INTO exercises (category_id, question, explanation, difficulty) VALUES
('prova-ponto-virgula', 'Em qual alternativa o ponto e vírgula está sendo usado corretamente para separar orações com sujeitos diferentes?', 'O ponto e vírgula é usado para separar orações coordenadas com sujeitos diferentes.', 5),
('prova-ponto-virgula', 'Identifique a opção em que o ponto e vírgula está sendo usado corretamente em uma enumeração de exemplos:', 'O ponto e vírgula é usado para separar exemplos em uma enumeração, especialmente quando são extensos.', 5),
('prova-ponto-virgula', 'Qual alternativa apresenta o uso correto do ponto e vírgula em uma lista de definições?', 'O ponto e vírgula é usado para separar diferentes definições em uma lista.', 5),
('prova-ponto-virgula', 'Em qual das opções o ponto e vírgula está sendo usado corretamente para separar orações com verbos diferentes?', 'O ponto e vírgula é usado para separar orações coordenadas com verbos diferentes.', 5),
('prova-ponto-virgula', 'Identifique a frase em que o ponto e vírgula está sendo usado corretamente em um texto filosófico:', 'Em textos filosóficos, o ponto e vírgula é usado para separar diferentes argumentos ou ideias.', 5),
('prova-ponto-virgula', 'Qual alternativa apresenta o uso correto do ponto e vírgula em uma sequência de orações independentes?', 'O ponto e vírgula é usado para separar orações independentes relacionadas pelo sentido.', 5),
('prova-ponto-virgula', 'Em qual frase o ponto e vírgula está sendo usado corretamente em uma enumeração com explicações?', 'O ponto e vírgula é usado para separar itens em uma enumeração quando esses itens contêm explicações.', 5),
('prova-ponto-virgula', 'Identifique a opção em que o ponto e vírgula está sendo usado corretamente em um texto técnico:', 'Em textos técnicos, o ponto e vírgula é usado para separar diferentes especificações ou características.', 5),
('prova-ponto-virgula', 'Qual alternativa apresenta o uso correto do ponto e vírgula em uma citação direta?', 'Em citações diretas, o ponto e vírgula é usado para separar diferentes partes da citação.', 5),
('prova-ponto-virgula', 'Em qual das opções o ponto e vírgula está sendo usado corretamente para separar itens em uma lista de procedimentos?', 'Em listas de procedimentos, o ponto e vírgula é usado para separar etapas complexas.', 5),
('prova-ponto-virgula', 'Identifique a frase em que o ponto e vírgula está sendo usado corretamente em um texto acadêmico:', 'Em textos acadêmicos, o ponto e vírgula é usado para separar diferentes argumentos ou evidências.', 5),
('prova-ponto-virgula', 'Qual alternativa apresenta o uso correto do ponto e vírgula em uma referência bibliográfica?', 'Em referências bibliográficas, o ponto e vírgula é usado para separar diferentes autores ou obras.', 5),
('prova-ponto-virgula', 'Em qual frase o ponto e vírgula está sendo usado corretamente para separar itens em uma enumeração com subdivisões?', 'O ponto e vírgula é usado para separar itens em uma enumeração quando esses itens contêm subdivisões.', 5),
('prova-ponto-virgula', 'Identifique a opção em que o ponto e vírgula está sendo usado corretamente para separar considerandos em documentos oficiais:', 'Em documentos oficiais, o ponto e vírgula é usado para separar considerandos ou justificativas.', 5),
('prova-ponto-virgula', 'Qual alternativa apresenta o uso correto do ponto e vírgula em uma lista de especificações técnicas?', 'Em listas de especificações técnicas, o ponto e vírgula é usado para separar diferentes especificações.', 5),
('prova-ponto-virgula', 'Em qual das opções o ponto e vírgula está sendo usado corretamente em um período composto por coordenação?', 'O ponto e vírgula é usado para separar orações em um período composto por coordenação quando não há conjunção.', 5),
('prova-ponto-virgula', 'Identifique a frase em que o ponto e vírgula está sendo usado corretamente em uma lista de ingredientes:', 'Em listas de ingredientes complexas, o ponto e vírgula é usado para separar grupos de ingredientes.', 5),
('prova-ponto-virgula', 'Qual alternativa apresenta o uso correto do ponto e vírgula em uma enumeração de características?', 'O ponto e vírgula é usado para separar características em uma enumeração, especialmente quando são detalhadas.', 5),
('prova-ponto-virgula', 'Em qual frase o ponto e vírgula está sendo usado corretamente em um texto literário?', 'Em textos literários, o ponto e vírgula é usado para criar pausas mais longas que a vírgula, mas menos definitivas que o ponto.', 5),
('prova-ponto-virgula', 'Identifique a opção em que o ponto e vírgula está sendo usado corretamente em uma lista técnica:', 'Em listas técnicas, o ponto e vírgula é usado para separar itens, especialmente quando são complexos.', 5);
